name: open edge for testing first jobs
on: 
  workflow_dispatch:
jobs:
  nexus_job_for_pass:
    runs-on: [self-hosted, nexus_server]
    outputs:
      output1: ${{ steps.string.outputs.test }}
    steps:
      - name: set env variable
        id: string
        run: |
           type C:\Users\Administrator\second.txt 
  
      - name: Conditionally Run
        if: steps.string.outputs.output1 == 'PASS'
        run: psexec -i 2 C:\Users\Administrator\Desktop\demo.bat
