name: open edge for testing first jobs
on: 
  workflow_dispatch:
jobs:
  nexus_job_for_pass:
    runs-on: [self-hosted, nexus_server]
    outputs:
      matrix: ${{ steps.string.outputs.matrix }}
    steps:
      - name: set env variable
        id: string
        run: echo "matrix= $(type C:\Users\Administrator\second.txt)" >> $GITHUB_ENV
  
      - name: Conditionally Run
        if: contains(env.matrix == 'PASS')
        run: psexec -i 2 C:\Users\Administrator\Desktop\demo.bat
