name: open edge for testing first jobs
on: 
  workflow_dispatch:
jobs:
  nexus_job:
    runs-on: [self-hosted, nexus_server]
    steps:
      - name: Run a nexus bat file 
        run: psexec -i 2 C:\Users\Administrator\Desktop\second.bat

      - name: run a bat file
        id: test
        run: psexec -i 2 C:\Users\Administrator\Desktop\test.bat

      - name: robot scripts exited with failure status
        if: ${{ failure() && steps.test.conclusion == 'failure' }}

    #  - name: get the condition
     #   run:  type "PROJECT_TO_TEST= $(C:\Users\Administrator\second.txt)" >> $GITHUB_ENV

     # - name: Conditionally Run
      #  if:   contains(env.PROJECT_TO_TEST, 'PASS')
      #  run:  echo "SomeString did exist and should run"
        
     # - name: Conditionally Run
     #   if:   contains(env.PROJECT_TO_TEST, 'FAIL')
     #   run:  echo "ShouldNotRun"  

      
