name: open edge for testingt
on: 
  workflow_dispatch:
jobs:
  nexus_job:
    runs-on: self-hosted
    steps:
      - name: Run a nexus bat file 
        run: psexec -i 2 C:\Users\Administrator\Desktop\nexus.bat
