name: open edge for testing first jobs
on: 
  push:
     branches:
       - main
jobs:
  nexus_job:
    runs-on: self-hosted
    steps:
      - name: Run a nexus bat file 
        run: psexec -i 2 C:\Users\Administrator\Desktop\second.bat
