name: open edge for testing first job
on: 
  push:
     branches:
          main
jobs:
  nexus_job:
    runs-on: self-hosted
    steps:
      - name: Run a nexus bat files
        run: C:\Users\Administrator\Desktop\first.bat
