name: open edge for test
on:
   push:
    branches:
       - main
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: run a nexus bat file- 1
        run: psexec.exe -s -d cmd.exe /c   "C:\Users\Administrator\Desktop\nexus.bat"
