name: open edge for test
on:
   push:
    branches:
       - main
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: Run a nexus bat file 
        run: psexec -i 2 C:\Users\Administrator\Desktop\nexus.bat
