name: open edge
on:
   push:
    branches:
       - main
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: run a nexus bat file
        run: psexec -i 1 C:\Users\Administrator\Desktop\nexus.bat
