name: open edge for test
on:
   push:
    branches:
       - main
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: run a nexus bat file for test
        run: psexec -i 2 C:\Users\Administrator\Desktop\nexus.bat
