name: open edge for testing first jobs
on: 
  workflow_dispatch:
jobs:
  nexus_job_for_pass:
    runs-on: [self-hosted, nexus_server]
    steps:
      - name: set env variable
        id: string
        run: |
           type C:\Users\Administrator\second.txt
  
   # Then you can use it in your if statement like so 
      - name: Conditionally Run
        if: "${{ needs.nexus_job_for_pass.outputs.output1 == 'PASS' }}"
        run: psexec -i 2 C:\Users\Administrator\Desktop\demo.bat
