name: open edge for testing first jobs
on: 
  workflow_dispatch:
jobs:
  nexus_job:
    runs-on: [self-hosted, nexus_server]
    steps:
      - name: set env variable
        run: |
           echo "PROJECT_TO_TEST=$(type C:\Users\Administrator\Desktop\second.bat)" >> $GITHUB_ENV
  
   # Then you can use it in your if statement like so 
      - name: Conditionally Run
        if: contains(env.PROJECT_TO_TEST, 'PASS')
        run: psexec -i 2 C:\Users\Administrator\Desktop\demo.bat
